# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loam < Formula
  desc "An Embedded Reactive & Transactional Engine for Content & Metadata."
  homepage "https://github.com/aretw0/loam"
  version "0.10.8"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aretw0/loam/releases/download/v0.10.8/loam_Darwin_x86_64.tar.gz"
      sha256 "d35383ceabf6826478f4c116fe2eab1daddd8fccc058877fa22c020b5c03cea3"

      def install
        bin.install "loam"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aretw0/loam/releases/download/v0.10.8/loam_Darwin_arm64.tar.gz"
      sha256 "40b2a1385bc49b870ef02c9b4e927a25c7f05673677ef33ee96a4120affac002"

      def install
        bin.install "loam"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aretw0/loam/releases/download/v0.10.8/loam_Linux_x86_64.tar.gz"
      sha256 "9d2df54a3110e5371b51dae467d49ed7a6380364dcc436f08fc049f63a50aeda"
      def install
        bin.install "loam"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aretw0/loam/releases/download/v0.10.8/loam_Linux_arm64.tar.gz"
      sha256 "c80faf54e693268ccd64508869c883c7444e073a36290257088e277f399b627a"
      def install
        bin.install "loam"
      end
    end
  end
end
