# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trellis < Formula
  desc "Deterministic state machine engine for CLIs and automation."
  homepage "https://github.com/aretw0/trellis"
  version "0.7.4"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aretw0/trellis/releases/download/v0.7.4/trellis_Darwin_x86_64.tar.gz"
      sha256 "6f7c433ef7069c5bcf5fd42055eb41853fea027bf940a683257687bd2a3b70b7"

      def install
        bin.install "trellis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aretw0/trellis/releases/download/v0.7.4/trellis_Darwin_arm64.tar.gz"
      sha256 "ecab1acfeed8df05c1b1f04732e68b537c4ab94f8f6ab503336bd402d2217c42"

      def install
        bin.install "trellis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aretw0/trellis/releases/download/v0.7.4/trellis_Linux_x86_64.tar.gz"
      sha256 "ae3a934c2fefe8be1859b643be2a3a5627041b9a22853d82924a2d3e6f449ab5"
      def install
        bin.install "trellis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aretw0/trellis/releases/download/v0.7.4/trellis_Linux_arm64.tar.gz"
      sha256 "223a561b6b1f28bb55448a86c8bb9e5600d0a8fbb1e14abc99be23d295926c10"
      def install
        bin.install "trellis"
      end
    end
  end
end
