# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trellis < Formula
  desc "Deterministic state machine engine for CLIs and automation."
  homepage "https://github.com/aretw0/trellis"
  version "0.7.14"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aretw0/trellis/releases/download/v0.7.14/trellis_Darwin_x86_64.tar.gz"
      sha256 "785b7244fc42e5a1c3a8570294d39be2c82c81e47cc79f324a2d84d81d45ff64"

      define_method(:install) do
        bin.install "trellis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aretw0/trellis/releases/download/v0.7.14/trellis_Darwin_arm64.tar.gz"
      sha256 "d81a6718c2e1d452671f14dcf3399d2a742dc103bae2366c01b749253a2fe30d"

      define_method(:install) do
        bin.install "trellis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aretw0/trellis/releases/download/v0.7.14/trellis_Linux_x86_64.tar.gz"
      sha256 "a3623031612b32747a7850714585eb65342eb3c39075752adfe806f3bf820cc7"
      define_method(:install) do
        bin.install "trellis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aretw0/trellis/releases/download/v0.7.14/trellis_Linux_arm64.tar.gz"
      sha256 "b19fc5f84ae0fab676d7ff09752ea14b8110d18eab1f8a35ef9ae0c52a4fdd41"
      define_method(:install) do
        bin.install "trellis"
      end
    end
  end
end
